---
title: "Прогнозирование цены подержанного автомобиля"
author: "Поменяй меня!"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)
options(width = 100) # ширина текстового вывода
options(digits = 3) # число знаков после запятой в выводе 
```

# Задание

В файле `kuiper.xlsx` содержатся данные о характеристиках и цене продажи порядка 800 легковых автомобилей. Данные представляют собой случайную выборку из базы данных Kelly's Blue Book, сделанную в 2005 году. Все автомобили в наборе данных были в эксплуатации менее года и находятся в отличном состоянии.

**Описание переменных**

- Price: рекомендованная цена продажи (целевая переменная)
- Mileage: пробег автомобиля в милях
- Make: производитель (Saturn, Pontiac, Chevrolet и др.)
- Model: конкретная модель (Ion, Vibe, Cavalier и др.)
- Trim: тип модели (SE Sedan 4D, Quad Coupe 2D и др)
- Type: тип кузова (седан, купе и др)
- Cylinder: количество цилиндров двигателя
- Liter: объекм двигателя
- Doors: количество дверей
- Cruise: есть ли круиз-контроль (1 = cruise)
- Sound: тип аудиосистемы (1 = upgraded)
- Leather: кожаные сидения(1 = leather)


**Требуется:**
1. С помощью разведочного анализа и построения модели множественной регрессии в R выявить, какие факторы и каким образом влияют на цену продажи автомобиля.

2. Исследовать качество и адекватность полученной вами модели. При необходимости, изменить модель или преобразовать данные так, чтобы проблемы были максимально устранены.

3. Найдите в таблице машины, цена которых существенно ниже рекомендованной вашей моделью (т.е. недооцененные машины).

По работе необходимо подготовить отчет в HTML-формате, подробно поясняющий ваши решения в процессе исследования данных, выбора факторов и построения модели, проверки ее адекватности.

# Как сдавать
Пришлите работу в формате HTML на мой email. Можно работать в небольших группах (2-3 человека).
