---
title: "Predicting employee turnover"
author: <put your name here>
output: 
  html_document: 
    toc: true
    toc_float: true
---

# Introduction

In this assignment you'll practice your data visualization and modeling skills for exploring factors correlated with employee turnover. Your objective is to build a set of hypotheses regarding the factors contributing towards turnover using the exploratory data analysis. Also, you'll need to build and to compare a few models based on different decision tree algorithms to check, if these hypotheses are supported by the modeling results.

## Attribute information:

The data was downloaded from Kaggle. Each row represents an employee; each column contains employee attributes:

* `satisfaction_level` (0–10)
* `last_evaluation` (The score from the last performance evaluation, 0-10)
* `number_project` (Number of projects completed while at work)
* `average_monthly_hours` (Average monthly hours at workplace)
* `time_in_company` (Time spent at the company in years)
* `Work_accident` (Whether the employee had a workplace accident)
* `left` (Whether the employee left the workplace or not (1 or 0))
* `promotion_last_5years` (Whether the employee was promoted in the last five years)
* `department` (Department in which they work for)
* `salary` (Relative level of salary)

# Assignment

1. Do the exploratory analysis to find factors correlated with the employee turnover

2. Using the training data, build a few models using rpart, ctree and C5.0 algorithms. Allow to use all the available variables.  Does the model agree with your initial hypotheses from EDA?

3. If you find out that the model ignores important relationships you've detected visually, try to force inclusion of these. You may need to adjust the parameters influencing the tree complexity. 

4. Let's consider a situation, where the company doesn't survey its employees to understand the job satisfaction level. What is the cost of missing information about the job satisfaction level in terms of the performance of the turnover prediction model? Compare the accuracy of the models with and without the satisfaction level variable.

